#!/bin/bash
if [ $# = 0 ];then
    echo "Error : hostname is empty !
Input like : root@47.106.119.0 ! "
else
    #cd ../../
    #mvn clean package
    ./cp_jars

    sed -i 's/^M//g' ./restartJp
    sed -i 's/^M//g' ./restartDev
    scp -r ./restartJp ./restartDev ./jars/*  $1:/usr/local/src/
    ssh $1 "/usr/local/src/restartDev"
fi


