#!/bin/bash
source /etc/profile
if [ '' = ${JAVA_HOME} ];then
    echo 'Error : JAVA_HOME is need !'
else

    /usr/local/src/stopJp ${1}
    if [ $? = 1 ];then
        /usr/local/src/startJp ${1} ${2}
    fi

fi


