#!/bin/bash
source /etc/profile
if [ '' = ${JAVA_HOME} ];then
    echo 'Error : JAVA_HOME is need !'
else

    if [ '' = "${3}" ];then
        echo 'Error : Xmx is need !'
    else
        /usr/local/src/stopJp ${1}
        if [ $? = 1 ];then
            /usr/local/src/startJp ${1} ${2} ${3} ${4}
        fi
    fi
fi


